#ifndef _GAME_RUNNER_H
#define _GAME_RUNNER_H

class GameRunner {
private:
	Board *original_board; // Board generated by the program
	Board *player_board; // Board that the player "drew"
	Board *optimal_path_board; // Board containing the optimal path
	BoardRenderer *original_board_renderer;
	BoardRenderer *player_board_renderer;
	BoardRenderer *optimal_path_board_renderer;
	int start_height, start_width, end_width, end_height;
	// Helper function that checks if the player wants to go out of bounds
	// or cross the start point/line segment
	bool is_available(std::vector<std::vector<int> > &field, Direction direction, int curr_h, int curr_w);
	// Helper function that checks if the players path hit any walls
	// returns true if it did
	bool check_path(std::vector<std::pair<int, int> > &path);
public:
	GameRunner(Board *original_board);
	// Prints the hello message
	void print_starting_message();
	// Starts the game
	void start_game();
	Board* get_original_board();
	Board* get_player_board();
	void set_original_board(Board *original_board);
	void set_player_board(Board *player_board);
	// Uses BFS to find one of the optimal paths
	void calculate_optimal_path(std::vector<std::pair<int, int> > &optimal_path);
};

#endif
